### ISSUE TITLE
Add ability of start new session

### ISSUE THREAD

**Issue by maidmaid** [meons/HESSO-Tourism-AndroidApp#2]

**Comment by ZHB** [comment]
![screenshot_2015-08-28-17-37-29](https://cloud.githubusercontent.com/assets/219280/9550465/cff6a7fc-4dab-11e5-8c90-0fef74d133e1.png)

This possibility would be in the top right corner of the navigation drawer.

**Comment by maidmaid** [comment]
:+1:
