### ISSUE TITLE
Define tutorial screens to show

### ISSUE THREAD

**Issue by ZHB** [meons/HESSO-Tourism-AndroidApp#7]
At the moment we have those slides, but it's just for example.

This tuto is only launches once after app installation or if we reset it in app settings.

![screenshot_2015-08-28-17-50-30](https://cloud.githubusercontent.com/assets/219280/9550786/b8f3fb0c-4dad-11e5-870d-2e0440405cf9.png)

![screenshot_2015-08-28-17-50-43](https://cloud.githubusercontent.com/assets/219280/9550813/dd881570-4dad-11e5-9738-a7041ad8bfa4.png)

![screenshot_2015-08-28-17-50-46](https://cloud.githubusercontent.com/assets/219280/9550843/f8b49850-4dad-11e5-81a1-627fac242f28.png)

**Comment by maidmaid** [comment]
:+1:
